#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys


def factorize():
    """
    A function to search file and factorize
    the given set of numbers into two prime numbers (format n = p*q)
    """
    try:
        arg = sys.argv[1]
        with open(arg) as file:
            for count in file:
                count = int(count)
                if count % 2 == 0:
                        print("{}={}*{}".format(count, count // 2, 2))
                        continue
                i = 3
                while i < count // 2:
                    if count % i == 0:
                        print("{}={}*{}".format(count, count // i, i))
                        break
                    i = i + 2
                if i == (count // 2) + 1:
                    print("{}={}*{}".format(count, count, 1))
    except (IndexError):
        pass


factorize()
